[build]
  command = "pnpm install && pnpm turbo build --filter=web"
  publish = "apps/web/dist/client"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["node_modules/@takumi-rs/core-linux-x64-gnu/**/*.*"]
