/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as searchRouteRouteImport } from './routes/(search)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as searchIndexRouteImport } from './routes/(search)/index'
import { Route as AuthenticatedAtChar123usernameChar125IndexRouteImport } from './routes/_authenticated/@{$username}/index'
import { Route as searchSearchIndexRouteImport } from './routes/(search)/search/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authRequestPasswordResetIndexRouteImport } from './routes/(auth)/request-password-reset/index'
import { Route as AuthenticatedToolsSlugIndexRouteImport } from './routes/_authenticated/tools/$slug/index'
import { Route as AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport } from './routes/_authenticated/@{$username}/add-tool/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const searchRouteRoute = searchRouteRouteImport.update({
  id: '/(search)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const searchIndexRoute = searchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => searchRouteRoute,
} as any)
const AuthenticatedAtChar123usernameChar125IndexRoute =
  AuthenticatedAtChar123usernameChar125IndexRouteImport.update({
    id: '/@{$username}/',
    path: '/@{$username}/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const searchSearchIndexRoute = searchSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => searchRouteRoute,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authRequestPasswordResetIndexRoute =
  authRequestPasswordResetIndexRouteImport.update({
    id: '/request-password-reset/',
    path: '/request-password-reset/',
    getParentRoute: () => authRouteRoute,
  } as any)
const AuthenticatedToolsSlugIndexRoute =
  AuthenticatedToolsSlugIndexRouteImport.update({
    id: '/tools/$slug/',
    path: '/tools/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125AddToolIndexRoute =
  AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport.update({
    id: '/@{$username}/add-tool/',
    path: '/@{$username}/add-tool/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof searchIndexRoute
  '/request-password-reset': typeof authRequestPasswordResetIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/search': typeof searchSearchIndexRoute
  '/@{$username}': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/@{$username}/add-tool': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/tools/$slug': typeof AuthenticatedToolsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof searchIndexRoute
  '/request-password-reset': typeof authRequestPasswordResetIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/search': typeof searchSearchIndexRoute
  '/@{$username}': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/@{$username}/add-tool': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/tools/$slug': typeof AuthenticatedToolsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(search)': typeof searchRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(search)/': typeof searchIndexRoute
  '/(auth)/request-password-reset/': typeof authRequestPasswordResetIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/(search)/search/': typeof searchSearchIndexRoute
  '/_authenticated/@{$username}/': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/_authenticated/@{$username}/add-tool/': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/_authenticated/tools/$slug/': typeof AuthenticatedToolsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request-password-reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/search'
    | '/@{$username}'
    | '/@{$username}/add-tool'
    | '/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request-password-reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/search'
    | '/@{$username}'
    | '/@{$username}/add-tool'
    | '/tools/$slug'
  id:
    | '__root__'
    | '/(auth)'
    | '/(search)'
    | '/_authenticated'
    | '/(search)/'
    | '/(auth)/request-password-reset/'
    | '/(auth)/reset-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
    | '/(search)/search/'
    | '/_authenticated/@{$username}/'
    | '/_authenticated/@{$username}/add-tool/'
    | '/_authenticated/tools/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  searchRouteRoute: typeof searchRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(search)': {
      id: '/(search)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof searchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(search)/': {
      id: '/(search)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof searchIndexRouteImport
      parentRoute: typeof searchRouteRoute
    }
    '/_authenticated/@{$username}/': {
      id: '/_authenticated/@{$username}/'
      path: '/@{$username}'
      fullPath: '/@{$username}'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(search)/search/': {
      id: '/(search)/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof searchSearchIndexRouteImport
      parentRoute: typeof searchRouteRoute
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/request-password-reset/': {
      id: '/(auth)/request-password-reset/'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof authRequestPasswordResetIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/tools/$slug/': {
      id: '/_authenticated/tools/$slug/'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof AuthenticatedToolsSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/@{$username}/add-tool/': {
      id: '/_authenticated/@{$username}/add-tool/'
      path: '/@{$username}/add-tool'
      fullPath: '/@{$username}/add-tool'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authRequestPasswordResetIndexRoute: typeof authRequestPasswordResetIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authRequestPasswordResetIndexRoute: authRequestPasswordResetIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface searchRouteRouteChildren {
  searchIndexRoute: typeof searchIndexRoute
  searchSearchIndexRoute: typeof searchSearchIndexRoute
}

const searchRouteRouteChildren: searchRouteRouteChildren = {
  searchIndexRoute: searchIndexRoute,
  searchSearchIndexRoute: searchSearchIndexRoute,
}

const searchRouteRouteWithChildren = searchRouteRoute._addFileChildren(
  searchRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtChar123usernameChar125IndexRoute: typeof AuthenticatedAtChar123usernameChar125IndexRoute
  AuthenticatedAtChar123usernameChar125AddToolIndexRoute: typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  AuthenticatedToolsSlugIndexRoute: typeof AuthenticatedToolsSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtChar123usernameChar125IndexRoute:
    AuthenticatedAtChar123usernameChar125IndexRoute,
  AuthenticatedAtChar123usernameChar125AddToolIndexRoute:
    AuthenticatedAtChar123usernameChar125AddToolIndexRoute,
  AuthenticatedToolsSlugIndexRoute: AuthenticatedToolsSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  searchRouteRoute: searchRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
