/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as searchRouteRouteImport } from './routes/(search)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as TermsOfServiceIndexRouteImport } from './routes/terms-of-service/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as searchIndexRouteImport } from './routes/(search)/index'
import { Route as AuthenticatedAtChar123usernameChar125RouteRouteImport } from './routes/_authenticated/@{$username}/route'
import { Route as AuthenticatedLeaderboardIndexRouteImport } from './routes/_authenticated/leaderboard/index'
import { Route as AuthenticatedAtChar123usernameChar125IndexRouteImport } from './routes/_authenticated/@{$username}/index'
import { Route as searchSearchIndexRouteImport } from './routes/(search)/search/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authRequestPasswordResetIndexRouteImport } from './routes/(auth)/request-password-reset/index'
import { Route as AuthenticatedToolsDirectoryIndexRouteImport } from './routes/_authenticated/tools/directory/index'
import { Route as AuthenticatedToolsAtChar123slugChar125IndexRouteImport } from './routes/_authenticated/tools/@{$slug}/index'
import { Route as AuthenticatedAtChar123usernameChar125SessionsIndexRouteImport } from './routes/_authenticated/@{$username}/sessions/index'
import { Route as AuthenticatedAtChar123usernameChar125SecurityIndexRouteImport } from './routes/_authenticated/@{$username}/security/index'
import { Route as AuthenticatedAtChar123usernameChar125DataIndexRouteImport } from './routes/_authenticated/@{$username}/data/index'
import { Route as AuthenticatedAtChar123usernameChar125BookmarksIndexRouteImport } from './routes/_authenticated/@{$username}/bookmarks/index'
import { Route as AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport } from './routes/_authenticated/@{$username}/add-tool/index'
import { Route as AuthenticatedAtChar123usernameChar125ActivityIndexRouteImport } from './routes/_authenticated/@{$username}/activity/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const searchRouteRoute = searchRouteRouteImport.update({
  id: '/(search)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceIndexRoute = TermsOfServiceIndexRouteImport.update({
  id: '/terms-of-service/',
  path: '/terms-of-service/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const searchIndexRoute = searchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => searchRouteRoute,
} as any)
const AuthenticatedAtChar123usernameChar125RouteRoute =
  AuthenticatedAtChar123usernameChar125RouteRouteImport.update({
    id: '/@{$username}',
    path: '/@{$username}',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardIndexRoute =
  AuthenticatedLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125IndexRoute =
  AuthenticatedAtChar123usernameChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const searchSearchIndexRoute = searchSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => searchRouteRoute,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authRequestPasswordResetIndexRoute =
  authRequestPasswordResetIndexRouteImport.update({
    id: '/request-password-reset/',
    path: '/request-password-reset/',
    getParentRoute: () => authRouteRoute,
  } as any)
const AuthenticatedToolsDirectoryIndexRoute =
  AuthenticatedToolsDirectoryIndexRouteImport.update({
    id: '/tools/directory/',
    path: '/tools/directory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsAtChar123slugChar125IndexRoute =
  AuthenticatedToolsAtChar123slugChar125IndexRouteImport.update({
    id: '/tools/@{$slug}/',
    path: '/tools/@{$slug}/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125SessionsIndexRoute =
  AuthenticatedAtChar123usernameChar125SessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125SecurityIndexRoute =
  AuthenticatedAtChar123usernameChar125SecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125DataIndexRoute =
  AuthenticatedAtChar123usernameChar125DataIndexRouteImport.update({
    id: '/data/',
    path: '/data/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125BookmarksIndexRoute =
  AuthenticatedAtChar123usernameChar125BookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125AddToolIndexRoute =
  AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport.update({
    id: '/add-tool/',
    path: '/add-tool/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)
const AuthenticatedAtChar123usernameChar125ActivityIndexRoute =
  AuthenticatedAtChar123usernameChar125ActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedAtChar123usernameChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/@{$username}': typeof AuthenticatedAtChar123usernameChar125RouteRouteWithChildren
  '/': typeof searchIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/terms-of-service': typeof TermsOfServiceIndexRoute
  '/request-password-reset': typeof authRequestPasswordResetIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/search': typeof searchSearchIndexRoute
  '/@{$username}/': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/leaderboard': typeof AuthenticatedLeaderboardIndexRoute
  '/@{$username}/activity': typeof AuthenticatedAtChar123usernameChar125ActivityIndexRoute
  '/@{$username}/add-tool': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/@{$username}/bookmarks': typeof AuthenticatedAtChar123usernameChar125BookmarksIndexRoute
  '/@{$username}/data': typeof AuthenticatedAtChar123usernameChar125DataIndexRoute
  '/@{$username}/security': typeof AuthenticatedAtChar123usernameChar125SecurityIndexRoute
  '/@{$username}/sessions': typeof AuthenticatedAtChar123usernameChar125SessionsIndexRoute
  '/tools/@{$slug}': typeof AuthenticatedToolsAtChar123slugChar125IndexRoute
  '/tools/directory': typeof AuthenticatedToolsDirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof searchIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/terms-of-service': typeof TermsOfServiceIndexRoute
  '/request-password-reset': typeof authRequestPasswordResetIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/search': typeof searchSearchIndexRoute
  '/@{$username}': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/leaderboard': typeof AuthenticatedLeaderboardIndexRoute
  '/@{$username}/activity': typeof AuthenticatedAtChar123usernameChar125ActivityIndexRoute
  '/@{$username}/add-tool': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/@{$username}/bookmarks': typeof AuthenticatedAtChar123usernameChar125BookmarksIndexRoute
  '/@{$username}/data': typeof AuthenticatedAtChar123usernameChar125DataIndexRoute
  '/@{$username}/security': typeof AuthenticatedAtChar123usernameChar125SecurityIndexRoute
  '/@{$username}/sessions': typeof AuthenticatedAtChar123usernameChar125SessionsIndexRoute
  '/tools/@{$slug}': typeof AuthenticatedToolsAtChar123slugChar125IndexRoute
  '/tools/directory': typeof AuthenticatedToolsDirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(search)': typeof searchRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/@{$username}': typeof AuthenticatedAtChar123usernameChar125RouteRouteWithChildren
  '/(search)/': typeof searchIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/terms-of-service/': typeof TermsOfServiceIndexRoute
  '/(auth)/request-password-reset/': typeof authRequestPasswordResetIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/(search)/search/': typeof searchSearchIndexRoute
  '/_authenticated/@{$username}/': typeof AuthenticatedAtChar123usernameChar125IndexRoute
  '/_authenticated/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/_authenticated/@{$username}/activity/': typeof AuthenticatedAtChar123usernameChar125ActivityIndexRoute
  '/_authenticated/@{$username}/add-tool/': typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  '/_authenticated/@{$username}/bookmarks/': typeof AuthenticatedAtChar123usernameChar125BookmarksIndexRoute
  '/_authenticated/@{$username}/data/': typeof AuthenticatedAtChar123usernameChar125DataIndexRoute
  '/_authenticated/@{$username}/security/': typeof AuthenticatedAtChar123usernameChar125SecurityIndexRoute
  '/_authenticated/@{$username}/sessions/': typeof AuthenticatedAtChar123usernameChar125SessionsIndexRoute
  '/_authenticated/tools/@{$slug}/': typeof AuthenticatedToolsAtChar123slugChar125IndexRoute
  '/_authenticated/tools/directory/': typeof AuthenticatedToolsDirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@{$username}'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/request-password-reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/search'
    | '/@{$username}/'
    | '/leaderboard'
    | '/@{$username}/activity'
    | '/@{$username}/add-tool'
    | '/@{$username}/bookmarks'
    | '/@{$username}/data'
    | '/@{$username}/security'
    | '/@{$username}/sessions'
    | '/tools/@{$slug}'
    | '/tools/directory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/request-password-reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/search'
    | '/@{$username}'
    | '/leaderboard'
    | '/@{$username}/activity'
    | '/@{$username}/add-tool'
    | '/@{$username}/bookmarks'
    | '/@{$username}/data'
    | '/@{$username}/security'
    | '/@{$username}/sessions'
    | '/tools/@{$slug}'
    | '/tools/directory'
  id:
    | '__root__'
    | '/(auth)'
    | '/(search)'
    | '/_authenticated'
    | '/_authenticated/@{$username}'
    | '/(search)/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/(auth)/request-password-reset/'
    | '/(auth)/reset-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
    | '/(search)/search/'
    | '/_authenticated/@{$username}/'
    | '/_authenticated/leaderboard/'
    | '/_authenticated/@{$username}/activity/'
    | '/_authenticated/@{$username}/add-tool/'
    | '/_authenticated/@{$username}/bookmarks/'
    | '/_authenticated/@{$username}/data/'
    | '/_authenticated/@{$username}/security/'
    | '/_authenticated/@{$username}/sessions/'
    | '/_authenticated/tools/@{$slug}/'
    | '/_authenticated/tools/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  searchRouteRoute: typeof searchRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  TermsOfServiceIndexRoute: typeof TermsOfServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(search)': {
      id: '/(search)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof searchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service/': {
      id: '/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(search)/': {
      id: '/(search)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof searchIndexRouteImport
      parentRoute: typeof searchRouteRoute
    }
    '/_authenticated/@{$username}': {
      id: '/_authenticated/@{$username}'
      path: '/@{$username}'
      fullPath: '/@{$username}'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125RouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard/': {
      id: '/_authenticated/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/@{$username}/': {
      id: '/_authenticated/@{$username}/'
      path: '/'
      fullPath: '/@{$username}/'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125IndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/(search)/search/': {
      id: '/(search)/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof searchSearchIndexRouteImport
      parentRoute: typeof searchRouteRoute
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/request-password-reset/': {
      id: '/(auth)/request-password-reset/'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof authRequestPasswordResetIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/tools/directory/': {
      id: '/_authenticated/tools/directory/'
      path: '/tools/directory'
      fullPath: '/tools/directory'
      preLoaderRoute: typeof AuthenticatedToolsDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/@{$slug}/': {
      id: '/_authenticated/tools/@{$slug}/'
      path: '/tools/@{$slug}'
      fullPath: '/tools/@{$slug}'
      preLoaderRoute: typeof AuthenticatedToolsAtChar123slugChar125IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/@{$username}/sessions/': {
      id: '/_authenticated/@{$username}/sessions/'
      path: '/sessions'
      fullPath: '/@{$username}/sessions'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125SessionsIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/_authenticated/@{$username}/security/': {
      id: '/_authenticated/@{$username}/security/'
      path: '/security'
      fullPath: '/@{$username}/security'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125SecurityIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/_authenticated/@{$username}/data/': {
      id: '/_authenticated/@{$username}/data/'
      path: '/data'
      fullPath: '/@{$username}/data'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125DataIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/_authenticated/@{$username}/bookmarks/': {
      id: '/_authenticated/@{$username}/bookmarks/'
      path: '/bookmarks'
      fullPath: '/@{$username}/bookmarks'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125BookmarksIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/_authenticated/@{$username}/add-tool/': {
      id: '/_authenticated/@{$username}/add-tool/'
      path: '/add-tool'
      fullPath: '/@{$username}/add-tool'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125AddToolIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
    '/_authenticated/@{$username}/activity/': {
      id: '/_authenticated/@{$username}/activity/'
      path: '/activity'
      fullPath: '/@{$username}/activity'
      preLoaderRoute: typeof AuthenticatedAtChar123usernameChar125ActivityIndexRouteImport
      parentRoute: typeof AuthenticatedAtChar123usernameChar125RouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authRequestPasswordResetIndexRoute: typeof authRequestPasswordResetIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authRequestPasswordResetIndexRoute: authRequestPasswordResetIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface searchRouteRouteChildren {
  searchIndexRoute: typeof searchIndexRoute
  searchSearchIndexRoute: typeof searchSearchIndexRoute
}

const searchRouteRouteChildren: searchRouteRouteChildren = {
  searchIndexRoute: searchIndexRoute,
  searchSearchIndexRoute: searchSearchIndexRoute,
}

const searchRouteRouteWithChildren = searchRouteRoute._addFileChildren(
  searchRouteRouteChildren,
)

interface AuthenticatedAtChar123usernameChar125RouteRouteChildren {
  AuthenticatedAtChar123usernameChar125IndexRoute: typeof AuthenticatedAtChar123usernameChar125IndexRoute
  AuthenticatedAtChar123usernameChar125ActivityIndexRoute: typeof AuthenticatedAtChar123usernameChar125ActivityIndexRoute
  AuthenticatedAtChar123usernameChar125AddToolIndexRoute: typeof AuthenticatedAtChar123usernameChar125AddToolIndexRoute
  AuthenticatedAtChar123usernameChar125BookmarksIndexRoute: typeof AuthenticatedAtChar123usernameChar125BookmarksIndexRoute
  AuthenticatedAtChar123usernameChar125DataIndexRoute: typeof AuthenticatedAtChar123usernameChar125DataIndexRoute
  AuthenticatedAtChar123usernameChar125SecurityIndexRoute: typeof AuthenticatedAtChar123usernameChar125SecurityIndexRoute
  AuthenticatedAtChar123usernameChar125SessionsIndexRoute: typeof AuthenticatedAtChar123usernameChar125SessionsIndexRoute
}

const AuthenticatedAtChar123usernameChar125RouteRouteChildren: AuthenticatedAtChar123usernameChar125RouteRouteChildren =
  {
    AuthenticatedAtChar123usernameChar125IndexRoute:
      AuthenticatedAtChar123usernameChar125IndexRoute,
    AuthenticatedAtChar123usernameChar125ActivityIndexRoute:
      AuthenticatedAtChar123usernameChar125ActivityIndexRoute,
    AuthenticatedAtChar123usernameChar125AddToolIndexRoute:
      AuthenticatedAtChar123usernameChar125AddToolIndexRoute,
    AuthenticatedAtChar123usernameChar125BookmarksIndexRoute:
      AuthenticatedAtChar123usernameChar125BookmarksIndexRoute,
    AuthenticatedAtChar123usernameChar125DataIndexRoute:
      AuthenticatedAtChar123usernameChar125DataIndexRoute,
    AuthenticatedAtChar123usernameChar125SecurityIndexRoute:
      AuthenticatedAtChar123usernameChar125SecurityIndexRoute,
    AuthenticatedAtChar123usernameChar125SessionsIndexRoute:
      AuthenticatedAtChar123usernameChar125SessionsIndexRoute,
  }

const AuthenticatedAtChar123usernameChar125RouteRouteWithChildren =
  AuthenticatedAtChar123usernameChar125RouteRoute._addFileChildren(
    AuthenticatedAtChar123usernameChar125RouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtChar123usernameChar125RouteRoute: typeof AuthenticatedAtChar123usernameChar125RouteRouteWithChildren
  AuthenticatedLeaderboardIndexRoute: typeof AuthenticatedLeaderboardIndexRoute
  AuthenticatedToolsAtChar123slugChar125IndexRoute: typeof AuthenticatedToolsAtChar123slugChar125IndexRoute
  AuthenticatedToolsDirectoryIndexRoute: typeof AuthenticatedToolsDirectoryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtChar123usernameChar125RouteRoute:
    AuthenticatedAtChar123usernameChar125RouteRouteWithChildren,
  AuthenticatedLeaderboardIndexRoute: AuthenticatedLeaderboardIndexRoute,
  AuthenticatedToolsAtChar123slugChar125IndexRoute:
    AuthenticatedToolsAtChar123slugChar125IndexRoute,
  AuthenticatedToolsDirectoryIndexRoute: AuthenticatedToolsDirectoryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  searchRouteRoute: searchRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  TermsOfServiceIndexRoute: TermsOfServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
